sudo: required
dist: trusty
env:
  global:
  - secure: HBqWsTtJIuk5lOW3MuSvuVDCxKoReYkZ4BRMwBnO4jdbHBP3VcEWYJunc4Vf7tGGuT7Fp6boT74su3rr8MDrU3V+gJRhckqIuN6gU3SOyhQvWxzgc50PFk6SX9Rr97eWxLPY6C22yTTx0ExvCu1UfoO+POizAHxjdCTyfVluNkAVgZ3NR7yPDiQMAFOhY2iZt4EUAsA4b0TxgmkpuRXOgzVfDTsNCk8u8yNWiNq6BWSwyeKdgI2zNmdVff7YMwRBkNrK0kmfET3VBTiWqijrYaqg5p9i3RosBqMnFFbkgG81sXAp5GJ0yJBTlN4JHcmKub2cK18Upu1fLiPsNqj33GH4DkkRyLr7W38MkisVyQLuAjknUJX2hPHp9el6wQv+YxM26q690ivhZMVW/FLZPrsx0t3uc5lIS6bMHavL7CsLhJeiELSdsnFGgaXD2cBMuEppkAXdHUd313qmoVO+bSFNCVSt6naFv1M47MdGDgiOSLFPbOn5yNYlY9GnMTbfiQmc5uiiBQyUUycibkvVSlAtCf/cm9b1FxZLRgDkARDWl+esHYxceV7iWdda7D4ktJvk1nCo5PmQLi2uVBTTCZWf5qxtCjZXpFIeEVh9lMqs8gxJEMf3IVtvQ//UnKp6qajut1k8FFvHzs9XhAvx1bRX/tYTQiBZnJLBOTyx0Hs=
  - secure: SUwT5Qpgm9BOSq8ewt8JmhT5mcZLP4XQfTUbpWLYGHyGHbFJ1FRdmwJKu/F4dm8rgbiJqrDrXN+cDP1Ael9ICEqCNihwiyRoG6SPhNQKRnM7kVZ8oivaY9XrxcL/lAYxfGNiqSM+jkdeTAZywjfdM8zIctkPtW3Gg2g1WhcBi5T8wFlDZk1PP1uTamEBAIL8hYHxkBl/J6wF3BsZmt6Hh1BqdrLrcpcU6P/UmctuPG+CQAGZD9Vbfxwqt6zqJqj7PS0tNT+ULEu2YGhOL796jI2ygq/Pt2dEoHfLXLa+XU1KvBuZXdkoBD1SWNN787e4gNrKPvKorY5JClYkBsOZgP/3LDRAaBr3kbAkgcyq4drRGqLhHEvze9U93QKO3v07PWVcPIbil0liqctlAhRNcPDWSIn0vWF9Y+L2tbZBJF31qqaLBLgYfmLMhrmYHdzJ7UuZnks7XhM5JbARbqUOC+2i9OqQYk9jkjNTUsFBX8j3DmmYAvrhrrwn4BzfLuNS5iTTq7zw52zLodEOQczEW4KpOsiWeaFkxdZFEFUX1CYDa8UOlMvUg6QOg4PrBpzr2j7S5Nr1dRuh8weg+ZdOzwEyk67t94yBLjEB8u3FXiBnM2jrqm+a/mya83x1IrAuUB4D/AcGdNfFyDo323nCC/7tMwxOFf/+TaO13UYNHr8=
  - secure: HsFsKHxbvgIcY3LlYGVFJwOnIiWvv9xmxk7R0HpS+G5TQSgFkpTpbavNzWU2I8kDbheMInIgOKP74bTnPlYLfmvKQMnja7WTjuUSLVqboCfQ4TpOWyBhHpZ8pPB/u7vltLOWKAhaUNM7yeAW430hO+RIgtNjKZjaouh9166rLUji5W7x5lm+7/JWf0CO+2HsCjECAfg0aPKhdtG3kFm8pPe57Kot8r2On+y5czW7HXdruIBouu5dYQJrZGE8FHr6PHvXjcol2hF2YxzYrdJAOKRuOuUaDHO5XB0ziIDVX9E0kunDgo/7OSPc7/egK5LqjfPPaHHbhO6EU9ju2RtuozXZ4F2743nJKH8QToUGK79VKvkKL6R39YRAAlP23yqxsme4GmfK3HYTcOO+Qm12O/gQ4DbE1VD51s3eGPZ7GvSofsJhma6fpc3OxR4Qbe2cE+tU8Ob6KxR5/KoKluIptdRQypnIN/9mxSxxsHr+TwPVKLmhwmV5C0madoSC8N/hPB7sKbk4uSfOmgMJAkMRAqbuaXU5WkqP43GCKNdQzEAuS2wnUNRewNRO5GM7dOOzgFbx45mqsZIKSVAhPC9MVG3ou3XKsqB7Xcps++6Z9CQkBPXxn1DbN6e5ptcFIva3E/3P5RXAnhDQcx/9+/YTSP2eRSn1iwTFSdTHF8spG7k=
  - secure: ol8Y4eMyDTkxbQiC9QobFEmuuZQ3Ep6dw2l7Si6wbW3X4F9cccbszyMeQt70MwwDoLyimWcH4PJKsrdUIC18qf0NKM8iIICggQqHQhp96kvXZ2Eo3PXkiJyMbWKUgWXrjlG37jSo/iZIeaH0/Epy1n+qzpem3QJxkyhs4dnhRG+uqbCCuxPs+OHQJriLkOv5MnkecFpVsr5OTdvK0Q75yZcQtQ56N6cQRsrCFCWyWZsev+fDvYhW4rJzQIjJx0emobyV4mPMFg1EYid4WOMsiU/KXUu1Vsf95Gm2s+93LHQCZoNZoJXxIfLwlCqNWcyDXhUgG1CHK0PmrSmDVjCqiPqUKh8tVj74HEtywEHioGYeyRlmNIwiNmznW9hXPkZyryYexZZ3aCQ1nod534SQ06vX+cGQOIz+z4doWb6Hw3RGVwrmPzedBWG+4P5bhZ3L1AiGoPAV9niZESCQ3Sbs+qFkdo22Me5fvLKCAc0orCv+ufVHBOjN3A9j70ZsroY2K+YGq7OWJtcH5LVNc4RrFCI1YtV/R5fraTTTCrb6BzHx/3n11NmFAfbBk/dpHmWTr7KBIvZCUfnQqDQ59UOCaMj/+whZXQRL1xrmEaHHFBSQTq9z91jSh8eGArsOogb6ftL6FhDzYwK7Af/QRKyt0CiJTysrcvgc4iZJy0jPa4g=
language: java
jdk:
- oraclejdk8
install:
- bash .travis/deploy-codesigning.sh
- bash .travis/update.sh
- export M2_HOME=/usr/share/maven3 && export PATH=${M2_HOME}/bin:${PATH} && export MAVEN_OPTS="-Xms2048m -Xmx2048m"
- java -version && javac -version && mvn -version -B
before_script:
- mvn dependency:resolve-plugins dependency:resolve -B -Prelease-ossrh -s configuration/settings.xml
script:
- mvn clean install -B -Dgpg.skip=true -s configuration/settings.xml
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.victims
